import java.text.SimpleDateFormat
gv_timeBeforeTest = null
gv_timeAfterTest = null
node()
{
    try {
    
    echo "**** Build Parameters ****"
    echo "base_image -> $base_image" 
    
    sh("rm -rf *")
    deleteDir()
    checkoutProject()
   // runJMeterScript()
    sh("rm -rf *")         
	}   
   catch (Exception e)
	{
        sh("rm -rf *") 
        println 'Exception encountered';      
        sh("docker rm -f masterjmeter")
        sh("docker rmi -f jmeterbase")
        sh("docker rmi -f jmetermaster")
        sh("docker rmi -f jmeterslave ")    		
		throw e 
	}
}

def checkoutProject()
{

    stage ('Checkout Project from Stash')
	{
		// Always check out the main repository, to grab any potential recent changes/pushes
    checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: "/home/ubuntu/jmeterrepo/"]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'ubuntu', url: "ssh://git@github.com:sjamesdaniel/JMeterTest.git"]]])
       }
}

def runJMeterScript()
{

    stage ('Run JMeter Script') 
	{		  	
    sh ("chmod 777 build.sh")
    sh ("chmod 777 build_images.sh ")
    echo "Build jmeter images test"
    sh ("./build_images.sh $app_name")    
    gv_timeBeforeTest = new Date().getTime().toString()
    echo "Begin jmeter test"
    sh ("./build.sh $app_name specperf")
	  gv_timeAfterTest = new Date().getTime().toString()
    sh("sleep 3m")	
	}
}


